name: dart2js_info
version: 0.6.1

description: >
  Libraries and tools to process data produced when running dart2js with
  --dump-info.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/dart2js_info/

environment:
  sdk: '>=2.0.0-dev.17.0 <3.0.0'

dependencies:
  args: ^1.4.3
  charcode: ^1.1.0
  collection: ^1.10.1
  fixnum: ^0.10.5
  path: ^1.3.6
  protobuf: ^0.10.0
  quiver: '>=0.29.0 <3.0.0'
  shelf: ^0.7.3
  shelf_static: ^0.2.4
  yaml: ^2.1.0

dev_dependencies:
  test: ^1.2.0

executables:
  dart2js_info: tools
